//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Validation.Dictionaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Academy.Validation.Dictionaries.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string external_menu_about {
            get {
                return ResourceManager.GetString("external.menu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string external_menu_articles {
            get {
                return ResourceManager.GetString("external.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string external_menu_contacts {
            get {
                return ResourceManager.GetString("external.menu.contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADEMY.
        /// </summary>
        public static string external_title {
            get {
                return ResourceManager.GetString("external.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string home_login_btn_login {
            get {
                return ResourceManager.GetString("home.login.btn.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string home_login_email {
            get {
                return ResourceManager.GetString("home.login.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string home_login_er_email_invalid {
            get {
                return ResourceManager.GetString("home.login.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify email address to login.
        /// </summary>
        public static string home_login_er_email_required {
            get {
                return ResourceManager.GetString("home.login.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify password to login.
        /// </summary>
        public static string home_login_er_pwd_required {
            get {
                return ResourceManager.GetString("home.login.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot the password?.
        /// </summary>
        public static string home_login_forgotpwd {
            get {
                return ResourceManager.GetString("home.login.forgotpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string home_login_lbl_signin {
            get {
                return ResourceManager.GetString("home.login.lbl.signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string home_login_pwd {
            get {
                return ResourceManager.GetString("home.login.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay online.
        /// </summary>
        public static string home_login_remember {
            get {
                return ResourceManager.GetString("home.login.remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string home_reg_bidthdate {
            get {
                return ResourceManager.GetString("home.reg.bidthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string home_reg_btn_register {
            get {
                return ResourceManager.GetString("home.reg.btn.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string home_reg_email {
            get {
                return ResourceManager.GetString("home.reg.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with specified email already exists.
        /// </summary>
        public static string home_reg_er_email_exists {
            get {
                return ResourceManager.GetString("home.reg.er.email.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string home_reg_er_email_invalid {
            get {
                return ResourceManager.GetString("home.reg.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string home_reg_er_email_required {
            get {
                return ResourceManager.GetString("home.reg.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string home_reg_er_fname_required {
            get {
                return ResourceManager.GetString("home.reg.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string home_reg_er_lname_required {
            get {
                return ResourceManager.GetString("home.reg.er.lname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have least 6 symbols.
        /// </summary>
        public static string home_reg_er_pwd_length {
            get {
                return ResourceManager.GetString("home.reg.er.pwd.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pssword is required.
        /// </summary>
        public static string home_reg_er_pwd_required {
            get {
                return ResourceManager.GetString("home.reg.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match the password.
        /// </summary>
        public static string home_reg_er_pwdconf_notmatch {
            get {
                return ResourceManager.GetString("home.reg.er.pwdconf.notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required.
        /// </summary>
        public static string home_reg_er_pwdconf_required {
            get {
                return ResourceManager.GetString("home.reg.er.pwdconf.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is required.
        /// </summary>
        public static string home_reg_er_university_required {
            get {
                return ResourceManager.GetString("home.reg.er.university.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string home_reg_fname {
            get {
                return ResourceManager.GetString("home.reg.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register if you do not have an account.
        /// </summary>
        public static string home_reg_lbl_register {
            get {
                return ResourceManager.GetString("home.reg.lbl.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string home_reg_lname {
            get {
                return ResourceManager.GetString("home.reg.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string home_reg_pwd {
            get {
                return ResourceManager.GetString("home.reg.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string home_reg_pwdconf {
            get {
                return ResourceManager.GetString("home.reg.pwdconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univercity.
        /// </summary>
        public static string home_reg_univercity {
            get {
                return ResourceManager.GetString("home.reg.univercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string internal_menu_articles {
            get {
                return ResourceManager.GetString("internal.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string internal_menu_exit {
            get {
                return ResourceManager.GetString("internal.menu.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string internal_menu_people {
            get {
                return ResourceManager.GetString("internal.menu.people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string internal_menu_profile {
            get {
                return ResourceManager.GetString("internal.menu.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADEMY.
        /// </summary>
        public static string internal_title {
            get {
                return ResourceManager.GetString("internal.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_eng {
            get {
                return ResourceManager.GetString("lang.eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lang_language {
            get {
                return ResourceManager.GetString("lang.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string lang_rus {
            get {
                return ResourceManager.GetString("lang.rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My questions.
        /// </summary>
        public static string prifile_myquestions {
            get {
                return ResourceManager.GetString("prifile.myquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string profile_edit_email {
            get {
                return ResourceManager.GetString("profile.edit.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string profile_edit_er_email_invalid {
            get {
                return ResourceManager.GetString("profile.edit.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string profile_edit_er_email_required {
            get {
                return ResourceManager.GetString("profile.edit.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fist name is required.
        /// </summary>
        public static string profile_edit_er_fname_required {
            get {
                return ResourceManager.GetString("profile.edit.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string profile_edit_er_lname {
            get {
                return ResourceManager.GetString("profile.edit.er.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string profile_edit_fname {
            get {
                return ResourceManager.GetString("profile.edit.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string profile_edit_lname {
            get {
                return ResourceManager.GetString("profile.edit.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string profile_edit_save {
            get {
                return ResourceManager.GetString("profile.edit.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My answers.
        /// </summary>
        public static string profile_myanswers {
            get {
                return ResourceManager.GetString("profile.myanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My articles.
        /// </summary>
        public static string profile_myarticles {
            get {
                return ResourceManager.GetString("profile.myarticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My comment.
        /// </summary>
        public static string profile_mycomment {
            get {
                return ResourceManager.GetString("profile.mycomment", resourceCulture);
            }
        }
    }
}
