//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Validation.Dictionaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Academy.Validation.Dictionaries.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer text.
        /// </summary>
        public static string answer_text {
            get {
                return ResourceManager.GetString("answer.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer text is required.
        /// </summary>
        public static string answer_text_err_required {
            get {
                return ResourceManager.GetString("answer.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description.
        /// </summary>
        public static string article_description {
            get {
                return ResourceManager.GetString("article.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description is required.
        /// </summary>
        public static string article_description_err_required {
            get {
                return ResourceManager.GetString("article.description.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article should have at least one discipline.
        /// </summary>
        public static string article_disciplines_err_required {
            get {
                return ResourceManager.GetString("article.disciplines.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string article_search_author {
            get {
                return ResourceManager.GetString("article.search.author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description.
        /// </summary>
        public static string article_search_description {
            get {
                return ResourceManager.GetString("article.search.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article title.
        /// </summary>
        public static string article_search_title {
            get {
                return ResourceManager.GetString("article.search.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article pdf file name.
        /// </summary>
        public static string article_source {
            get {
                return ResourceManager.GetString("article.source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file name is required.
        /// </summary>
        public static string article_source_err_required {
            get {
                return ResourceManager.GetString("article.source.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artcile title.
        /// </summary>
        public static string article_title {
            get {
                return ResourceManager.GetString("article.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article title is required.
        /// </summary>
        public static string article_title_err_required {
            get {
                return ResourceManager.GetString("article.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string author_email {
            get {
                return ResourceManager.GetString("author.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified email is not an email address.
        /// </summary>
        public static string author_email_err_invalid {
            get {
                return ResourceManager.GetString("author.email.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string author_email_err_required {
            get {
                return ResourceManager.GetString("author.email.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string author_firstname {
            get {
                return ResourceManager.GetString("author.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string author_firstname_err_required {
            get {
                return ResourceManager.GetString("author.firstname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string author_lastname {
            get {
                return ResourceManager.GetString("author.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string author_lastname_err_required {
            get {
                return ResourceManager.GetString("author.lastname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3eng.swf.
        /// </summary>
        public static string banner {
            get {
                return ResourceManager.GetString("banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment text.
        /// </summary>
        public static string comment_text {
            get {
                return ResourceManager.GetString("comment.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment text is required.
        /// </summary>
        public static string comment_text_err_required {
            get {
                return ResourceManager.GetString("comment.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 Academy.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string external_menu_about {
            get {
                return ResourceManager.GetString("external.menu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string external_menu_articles {
            get {
                return ResourceManager.GetString("external.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string external_menu_contacts {
            get {
                return ResourceManager.GetString("external.menu.contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string external_menu_questions {
            get {
                return ResourceManager.GetString("external.menu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADEMY.
        /// </summary>
        public static string external_title {
            get {
                return ResourceManager.GetString("external.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find articles.
        /// </summary>
        public static string internal_menu_articles {
            get {
                return ResourceManager.GetString("internal.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string internal_menu_exit {
            get {
                return ResourceManager.GetString("internal.menu.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        public static string internal_menu_profile {
            get {
                return ResourceManager.GetString("internal.menu.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions and answers.
        /// </summary>
        public static string internal_menu_questions {
            get {
                return ResourceManager.GetString("internal.menu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADEMY.
        /// </summary>
        public static string internal_title {
            get {
                return ResourceManager.GetString("internal.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_eng {
            get {
                return ResourceManager.GetString("lang.eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lang_language {
            get {
                return ResourceManager.GetString("lang.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string lang_rus {
            get {
                return ResourceManager.GetString("lang.rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_btn_login {
            get {
                return ResourceManager.GetString("login.btn.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string login_email {
            get {
                return ResourceManager.GetString("login.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string login_er_email_invalid {
            get {
                return ResourceManager.GetString("login.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify email address to login.
        /// </summary>
        public static string login_er_email_required {
            get {
                return ResourceManager.GetString("login.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify password to login.
        /// </summary>
        public static string login_er_pwd_required {
            get {
                return ResourceManager.GetString("login.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string login_err_failed {
            get {
                return ResourceManager.GetString("login.err.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot the password?.
        /// </summary>
        public static string login_forgotpwd {
            get {
                return ResourceManager.GetString("login.forgotpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string login_lbl_signin {
            get {
                return ResourceManager.GetString("login.lbl.signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string login_pwd {
            get {
                return ResourceManager.GetString("login.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay online.
        /// </summary>
        public static string login_remember {
            get {
                return ResourceManager.GetString("login.remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_submit {
            get {
                return ResourceManager.GetString("login.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo_eng.png.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mainmenu_about {
            get {
                return ResourceManager.GetString("mainmenu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find articles.
        /// </summary>
        public static string mainmenu_articles {
            get {
                return ResourceManager.GetString("mainmenu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string mainmenu_contacts {
            get {
                return ResourceManager.GetString("mainmenu.contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions and answers.
        /// </summary>
        public static string mainmenu_questions {
            get {
                return ResourceManager.GetString("mainmenu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note text.
        /// </summary>
        public static string note_text {
            get {
                return ResourceManager.GetString("note.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note text is required.
        /// </summary>
        public static string note_text_err_required {
            get {
                return ResourceManager.GetString("note.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note title.
        /// </summary>
        public static string note_title {
            get {
                return ResourceManager.GetString("note.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note title is required.
        /// </summary>
        public static string note_title_err_required {
            get {
                return ResourceManager.GetString("note.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My questions.
        /// </summary>
        public static string prifile_myquestions {
            get {
                return ResourceManager.GetString("prifile.myquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string profile_edit_email {
            get {
                return ResourceManager.GetString("profile.edit.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string profile_edit_er_email_invalid {
            get {
                return ResourceManager.GetString("profile.edit.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string profile_edit_er_email_required {
            get {
                return ResourceManager.GetString("profile.edit.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fist name is required.
        /// </summary>
        public static string profile_edit_er_fname_required {
            get {
                return ResourceManager.GetString("profile.edit.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string profile_edit_er_lname {
            get {
                return ResourceManager.GetString("profile.edit.er.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string profile_edit_fname {
            get {
                return ResourceManager.GetString("profile.edit.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string profile_edit_lname {
            get {
                return ResourceManager.GetString("profile.edit.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string profile_edit_save {
            get {
                return ResourceManager.GetString("profile.edit.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My answers.
        /// </summary>
        public static string profile_myanswers {
            get {
                return ResourceManager.GetString("profile.myanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My articles.
        /// </summary>
        public static string profile_myarticles {
            get {
                return ResourceManager.GetString("profile.myarticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My comments.
        /// </summary>
        public static string profile_mycomment {
            get {
                return ResourceManager.GetString("profile.mycomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New answers.
        /// </summary>
        public static string profile_newanswers {
            get {
                return ResourceManager.GetString("profile.newanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New articles.
        /// </summary>
        public static string profile_newarticles {
            get {
                return ResourceManager.GetString("profile.newarticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comments.
        /// </summary>
        public static string profile_newcomments {
            get {
                return ResourceManager.GetString("profile.newcomments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New questions.
        /// </summary>
        public static string profile_newquestions {
            get {
                return ResourceManager.GetString("profile.newquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one discipline should be selected.
        /// </summary>
        public static string question_disciplines_err_required {
            get {
                return ResourceManager.GetString("question.disciplines.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search keywords.
        /// </summary>
        public static string question_search_keyword {
            get {
                return ResourceManager.GetString("question.search.keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text.
        /// </summary>
        public static string question_text {
            get {
                return ResourceManager.GetString("question.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text is required.
        /// </summary>
        public static string question_text_err_required {
            get {
                return ResourceManager.GetString("question.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title.
        /// </summary>
        public static string question_title {
            get {
                return ResourceManager.GetString("question.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title is required.
        /// </summary>
        public static string question_title_err_required {
            get {
                return ResourceManager.GetString("question.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string registration__btn_register {
            get {
                return ResourceManager.GetString("registration..btn.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string registration_bidthdate {
            get {
                return ResourceManager.GetString("registration.bidthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string registration_email {
            get {
                return ResourceManager.GetString("registration.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with specified email already exists.
        /// </summary>
        public static string registration_er_email_exists {
            get {
                return ResourceManager.GetString("registration.er.email.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string registration_er_email_invalid {
            get {
                return ResourceManager.GetString("registration.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string registration_er_email_required {
            get {
                return ResourceManager.GetString("registration.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string registration_er_fname_required {
            get {
                return ResourceManager.GetString("registration.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string registration_er_lname_required {
            get {
                return ResourceManager.GetString("registration.er.lname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have least 6 symbols.
        /// </summary>
        public static string registration_er_pwd_length {
            get {
                return ResourceManager.GetString("registration.er.pwd.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pssword is required.
        /// </summary>
        public static string registration_er_pwd_required {
            get {
                return ResourceManager.GetString("registration.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match the password.
        /// </summary>
        public static string registration_er_pwdconf_notmatch {
            get {
                return ResourceManager.GetString("registration.er.pwdconf.notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required.
        /// </summary>
        public static string registration_er_pwdconf_required {
            get {
                return ResourceManager.GetString("registration.er.pwdconf.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is required.
        /// </summary>
        public static string registration_er_university_required {
            get {
                return ResourceManager.GetString("registration.er.university.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string registration_fname {
            get {
                return ResourceManager.GetString("registration.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register if you do not have an account.
        /// </summary>
        public static string registration_lbl_register {
            get {
                return ResourceManager.GetString("registration.lbl.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string registration_lname {
            get {
                return ResourceManager.GetString("registration.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string registration_pwd {
            get {
                return ResourceManager.GetString("registration.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string registration_pwdconf {
            get {
                return ResourceManager.GetString("registration.pwdconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string registration_submit {
            get {
                return ResourceManager.GetString("registration.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univercity.
        /// </summary>
        public static string registration_univercity {
            get {
                return ResourceManager.GetString("registration.univercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string user_birthdate {
            get {
                return ResourceManager.GetString("user.birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date is required.
        /// </summary>
        public static string user_birthdate_err_required {
            get {
                return ResourceManager.GetString("user.birthdate.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string user_email {
            get {
                return ResourceManager.GetString("user.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified email is not an email address.
        /// </summary>
        public static string user_email_err_invalid {
            get {
                return ResourceManager.GetString("user.email.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string user_email_err_required {
            get {
                return ResourceManager.GetString("user.email.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string user_firstname {
            get {
                return ResourceManager.GetString("user.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string user_firstname_err_requiered {
            get {
                return ResourceManager.GetString("user.firstname.err.requiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string user_lastname {
            get {
                return ResourceManager.GetString("user.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string user_lastname_err_required {
            get {
                return ResourceManager.GetString("user.lastname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string user_photo {
            get {
                return ResourceManager.GetString("user.photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string user_university {
            get {
                return ResourceManager.GetString("user.university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is required.
        /// </summary>
        public static string user_university_err_required {
            get {
                return ResourceManager.GetString("user.university.err.required", resourceCulture);
            }
        }
    }
}
