//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Validation.Dictionaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Academy.Validation.Dictionaries.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social network for scientists &quot;Academy&quot; was established in 2013..
        /// </summary>
        public static string about_p1 {
            get {
                return ResourceManager.GetString("about.p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our primary goal is to create a space that would combine the work of new and expectant scientists around the world, made it possible to use publications..
        /// </summary>
        public static string about_p2 {
            get {
                return ResourceManager.GetString("about.p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The technical features of the site include upload, download and comment on publications, create your profile with personal information, the confidentiality of which is guaranteed. You can also ask any question and get an answer, or leave a response yourself. Leave a note in your own profile to remember important events!.
        /// </summary>
        public static string about_p3 {
            get {
                return ResourceManager.GetString("about.p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wanted to create a resource accessible from anywhere in the world which would bring benefits to all, wishing to obtain reliable information from trusted sources..
        /// </summary>
        public static string about_p4 {
            get {
                return ResourceManager.GetString("about.p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet site &quot;Academy&quot; is specific. Our target audience is people with higher education and advanced degree (graduate degrees), as well as graduate students, masters - and all those who wants in the future to go into the social category of &quot;scientists.&quot; By registering here, you will always be able to find the information you need in the fields of Mathematics, Physics, Biology, and view questions / answers of colleagues and people of interest..
        /// </summary>
        public static string about_p5 {
            get {
                return ResourceManager.GetString("about.p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the change of language in order to view the &quot;Academy&quot; in the language of your choice conveniently. Upload a personal photo. Find your desired material by searching. Comment publication and thus facilitate the search for the rest of those who subscribe to this topic. Leave interesting discipline and get updates on everything going on in them! For best performance, use the website feedback form in the Contact section. We always welcome suggestions and feedback, we will answer all the questions..
        /// </summary>
        public static string about_p6 {
            get {
                return ResourceManager.GetString("about.p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like any aspiring project, we are going to grow, providing more and more functionality to users..
        /// </summary>
        public static string about_p7 {
            get {
                return ResourceManager.GetString("about.p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for choosing us!.
        /// </summary>
        public static string about_p8 {
            get {
                return ResourceManager.GetString("about.p8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social network for scientists &quot;Academy&quot;. Always on the pulse of science! © 2013.
        /// </summary>
        public static string about_p9 {
            get {
                return ResourceManager.GetString("about.p9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new article.
        /// </summary>
        public static string add_new_article {
            get {
                return ResourceManager.GetString("add.new.article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new note.
        /// </summary>
        public static string add_new_note {
            get {
                return ResourceManager.GetString("add.new.note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algebra.
        /// </summary>
        public static string algebra {
            get {
                return ResourceManager.GetString("algebra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytic geometry.
        /// </summary>
        public static string analytic_geometry {
            get {
                return ResourceManager.GetString("analytic.geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anatomy.
        /// </summary>
        public static string anatomy {
            get {
                return ResourceManager.GetString("anatomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add answer.
        /// </summary>
        public static string answer_add {
            get {
                return ResourceManager.GetString("answer.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer text.
        /// </summary>
        public static string answer_text {
            get {
                return ResourceManager.GetString("answer.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer text is required.
        /// </summary>
        public static string answer_text_err_required {
            get {
                return ResourceManager.GetString("answer.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show answers.
        /// </summary>
        public static string answers_show {
            get {
                return ResourceManager.GetString("answers.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthropology.
        /// </summary>
        public static string anthropology {
            get {
                return ResourceManager.GetString("anthropology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthropotomy.
        /// </summary>
        public static string anthropotomy {
            get {
                return ResourceManager.GetString("anthropotomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add author.
        /// </summary>
        public static string article_create_add_author {
            get {
                return ResourceManager.GetString("article.create.add.author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string article_create_modal_select {
            get {
                return ResourceManager.GetString("article.create.modal.select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select disciplines for article.
        /// </summary>
        public static string article_create_select_article_disciplines {
            get {
                return ResourceManager.GetString("article.create.select.article.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select disciplines.
        /// </summary>
        public static string article_create_select_disciplines {
            get {
                return ResourceManager.GetString("article.create.select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description.
        /// </summary>
        public static string article_description {
            get {
                return ResourceManager.GetString("article.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description is required.
        /// </summary>
        public static string article_description_err_required {
            get {
                return ResourceManager.GetString("article.description.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article should have at least one discipline.
        /// </summary>
        public static string article_disciplines_err_required {
            get {
                return ResourceManager.GetString("article.disciplines.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article file.
        /// </summary>
        public static string article_file {
            get {
                return ResourceManager.GetString("article.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string article_search_author {
            get {
                return ResourceManager.GetString("article.search.author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description.
        /// </summary>
        public static string article_search_description {
            get {
                return ResourceManager.GetString("article.search.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article title.
        /// </summary>
        public static string article_search_title {
            get {
                return ResourceManager.GetString("article.search.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles search.
        /// </summary>
        public static string article_serach_title {
            get {
                return ResourceManager.GetString("article.serach.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show article.
        /// </summary>
        public static string article_show {
            get {
                return ResourceManager.GetString("article.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article pdf file name.
        /// </summary>
        public static string article_source {
            get {
                return ResourceManager.GetString("article.source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file name is required.
        /// </summary>
        public static string article_source_err_required {
            get {
                return ResourceManager.GetString("article.source.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artcile title.
        /// </summary>
        public static string article_title {
            get {
                return ResourceManager.GetString("article.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article title is required.
        /// </summary>
        public static string article_title_err_required {
            get {
                return ResourceManager.GetString("article.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask question.
        /// </summary>
        public static string ask_question {
            get {
                return ResourceManager.GetString("ask.question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string author_email {
            get {
                return ResourceManager.GetString("author.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified email is not an email address.
        /// </summary>
        public static string author_email_err_invalid {
            get {
                return ResourceManager.GetString("author.email.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string author_email_err_required {
            get {
                return ResourceManager.GetString("author.email.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string author_firstname {
            get {
                return ResourceManager.GetString("author.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string author_firstname_err_required {
            get {
                return ResourceManager.GetString("author.firstname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string author_lastname {
            get {
                return ResourceManager.GetString("author.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string author_lastname_err_required {
            get {
                return ResourceManager.GetString("author.lastname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3eng.swf.
        /// </summary>
        public static string banner {
            get {
                return ResourceManager.GetString("banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bioacoustics.
        /// </summary>
        public static string bioacoustics {
            get {
                return ResourceManager.GetString("bioacoustics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bioenergetics.
        /// </summary>
        public static string bioenergetics {
            get {
                return ResourceManager.GetString("bioenergetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biology.
        /// </summary>
        public static string biology {
            get {
                return ResourceManager.GetString("biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biomechanics.
        /// </summary>
        public static string biomechanics {
            get {
                return ResourceManager.GetString("biomechanics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biophysics.
        /// </summary>
        public static string biophysics {
            get {
                return ResourceManager.GetString("biophysics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you  have any problems ba using the site or if you have any wishes,questions whatever,please feel free to contact us!.
        /// </summary>
        public static string cintacts_p2 {
            get {
                return ResourceManager.GetString("cintacts.p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination group theory.
        /// </summary>
        public static string combination_group_theory {
            get {
                return ResourceManager.GetString("combination.group.theory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinatorial topology.
        /// </summary>
        public static string combinatorial_topology {
            get {
                return ResourceManager.GetString("combinatorial.topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string comment_add {
            get {
                return ResourceManager.GetString("comment.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment text.
        /// </summary>
        public static string comment_text {
            get {
                return ResourceManager.GetString("comment.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment text is required.
        /// </summary>
        public static string comment_text_err_required {
            get {
                return ResourceManager.GetString("comment.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show comments.
        /// </summary>
        public static string comments_show {
            get {
                return ResourceManager.GetString("comments.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear users!.
        /// </summary>
        public static string contacts_p1 {
            get {
                return ResourceManager.GetString("contacts.p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you very much!.
        /// </summary>
        public static string contacts_p10 {
            get {
                return ResourceManager.GetString("contacts.p10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email the Head Office :.
        /// </summary>
        public static string contacts_p3 {
            get {
                return ResourceManager.GetString("contacts.p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alololo@gmail.com.
        /// </summary>
        public static string contacts_p4 {
            get {
                return ResourceManager.GetString("contacts.p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kororo@gmail.com.
        /// </summary>
        public static string contacts_p5 {
            get {
                return ResourceManager.GetString("contacts.p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or just call us:.
        /// </summary>
        public static string contacts_p6 {
            get {
                return ResourceManager.GetString("contacts.p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +25 (269) 12-3563.
        /// </summary>
        public static string contacts_p7 {
            get {
                return ResourceManager.GetString("contacts.p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +74 (021) 13-5684.
        /// </summary>
        public static string contacts_p8 {
            get {
                return ResourceManager.GetString("contacts.p8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +89 (589) 14-5692.
        /// </summary>
        public static string contacts_p9 {
            get {
                return ResourceManager.GetString("contacts.p9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 Academy.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential geometry.
        /// </summary>
        public static string differential_geometry {
            get {
                return ResourceManager.GetString("differential.geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential topology.
        /// </summary>
        public static string differential_topology {
            get {
                return ResourceManager.GetString("differential.topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplines.
        /// </summary>
        public static string disciplines {
            get {
                return ResourceManager.GetString("disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economical phytology.
        /// </summary>
        public static string economical_phytology {
            get {
                return ResourceManager.GetString("economical.phytology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embryology.
        /// </summary>
        public static string embryology {
            get {
                return ResourceManager.GetString("embryology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endocrinology.
        /// </summary>
        public static string endocrinology {
            get {
                return ResourceManager.GetString("endocrinology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.18051
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace Academy.Validation.Dictionaries {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string English_Designer {
            get {
                return ResourceManager.GetString("English_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental science.
        /// </summary>
        public static string environmental_science {
            get {
                return ResourceManager.GetString("environmental.science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string external_menu_about {
            get {
                return ResourceManager.GetString("external.menu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string external_menu_articles {
            get {
                return ResourceManager.GetString("external.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string external_menu_contacts {
            get {
                return ResourceManager.GetString("external.menu.contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string external_menu_questions {
            get {
                return ResourceManager.GetString("external.menu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADEMY.
        /// </summary>
        public static string external_title {
            get {
                return ResourceManager.GetString("external.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finite fields.
        /// </summary>
        public static string finite_fields {
            get {
                return ResourceManager.GetString("finite.fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General immunology.
        /// </summary>
        public static string general_immunology {
            get {
                return ResourceManager.GetString("general.immunology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General topology.
        /// </summary>
        public static string general_topology {
            get {
                return ResourceManager.GetString("general.topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genetic engineering.
        /// </summary>
        public static string genetic_engineering {
            get {
                return ResourceManager.GetString("genetic.engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genetics.
        /// </summary>
        public static string genetics {
            get {
                return ResourceManager.GetString("genetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genomics.
        /// </summary>
        public static string genomics {
            get {
                return ResourceManager.GetString("genomics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string geometry {
            get {
                return ResourceManager.GetString("geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group theory.
        /// </summary>
        public static string group_theory {
            get {
                return ResourceManager.GetString("group.theory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human physiology and zoophysics.
        /// </summary>
        public static string human_physiology_and_zoophysics {
            get {
                return ResourceManager.GetString("human.physiology.and.zoophysics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunology.
        /// </summary>
        public static string immunology {
            get {
                return ResourceManager.GetString("immunology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles search.
        /// </summary>
        public static string internal_menu_articles {
            get {
                return ResourceManager.GetString("internal.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string internal_menu_exit {
            get {
                return ResourceManager.GetString("internal.menu.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        public static string internal_menu_profile {
            get {
                return ResourceManager.GetString("internal.menu.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions &amp; answers.
        /// </summary>
        public static string internal_menu_questions {
            get {
                return ResourceManager.GetString("internal.menu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADEMY.
        /// </summary>
        public static string internal_title {
            get {
                return ResourceManager.GetString("internal.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_eng {
            get {
                return ResourceManager.GetString("lang.eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lang_language {
            get {
                return ResourceManager.GetString("lang.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string lang_rus {
            get {
                return ResourceManager.GetString("lang.rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_btn_login {
            get {
                return ResourceManager.GetString("login.btn.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string login_email {
            get {
                return ResourceManager.GetString("login.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string login_er_email_invalid {
            get {
                return ResourceManager.GetString("login.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify email address to login.
        /// </summary>
        public static string login_er_email_required {
            get {
                return ResourceManager.GetString("login.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify password to login.
        /// </summary>
        public static string login_er_pwd_required {
            get {
                return ResourceManager.GetString("login.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string login_err_failed {
            get {
                return ResourceManager.GetString("login.err.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot the password?.
        /// </summary>
        public static string login_forgotpwd {
            get {
                return ResourceManager.GetString("login.forgotpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string login_lbl_signin {
            get {
                return ResourceManager.GetString("login.lbl.signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string login_pwd {
            get {
                return ResourceManager.GetString("login.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay online.
        /// </summary>
        public static string login_remember {
            get {
                return ResourceManager.GetString("login.remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login_submit {
            get {
                return ResourceManager.GetString("login.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo_eng.png.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mainmenu_about {
            get {
                return ResourceManager.GetString("mainmenu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles search.
        /// </summary>
        public static string mainmenu_articles {
            get {
                return ResourceManager.GetString("mainmenu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string mainmenu_contacts {
            get {
                return ResourceManager.GetString("mainmenu.contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions &amp; answers.
        /// </summary>
        public static string mainmenu_questions {
            get {
                return ResourceManager.GetString("mainmenu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.
        /// </summary>
        public static string math {
            get {
                return ResourceManager.GetString("math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanics.
        /// </summary>
        public static string mechanics {
            get {
                return ResourceManager.GetString("mechanics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical physics.
        /// </summary>
        public static string medical_physics {
            get {
                return ResourceManager.GetString("medical.physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microrganism physiology.
        /// </summary>
        public static string microrganism_physiology {
            get {
                return ResourceManager.GetString("microrganism.physiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular genetics.
        /// </summary>
        public static string molecular_genetics {
            get {
                return ResourceManager.GetString("molecular.genetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Januar.
        /// </summary>
        public static string month1 {
            get {
                return ResourceManager.GetString("month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string month10 {
            get {
                return ResourceManager.GetString("month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string month11 {
            get {
                return ResourceManager.GetString("month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string month12 {
            get {
                return ResourceManager.GetString("month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Februar.
        /// </summary>
        public static string month2 {
            get {
                return ResourceManager.GetString("month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marth.
        /// </summary>
        public static string month3 {
            get {
                return ResourceManager.GetString("month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string month4 {
            get {
                return ResourceManager.GetString("month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string month5 {
            get {
                return ResourceManager.GetString("month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string month6 {
            get {
                return ResourceManager.GetString("month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string month7 {
            get {
                return ResourceManager.GetString("month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string month8 {
            get {
                return ResourceManager.GetString("month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string month9 {
            get {
                return ResourceManager.GetString("month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom physiology.
        /// </summary>
        public static string mushroom_physiology {
            get {
                return ResourceManager.GetString("mushroom.physiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        public static string note_add {
            get {
                return ResourceManager.GetString("note.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note text.
        /// </summary>
        public static string note_text {
            get {
                return ResourceManager.GetString("note.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note text is required.
        /// </summary>
        public static string note_text_err_required {
            get {
                return ResourceManager.GetString("note.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note title.
        /// </summary>
        public static string note_title {
            get {
                return ResourceManager.GetString("note.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note title is required.
        /// </summary>
        public static string note_title_err_required {
            get {
                return ResourceManager.GetString("note.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particular immunology.
        /// </summary>
        public static string particular_immunology {
            get {
                return ResourceManager.GetString("particular.immunology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philosophical anthropology.
        /// </summary>
        public static string philosophical_anthropology {
            get {
                return ResourceManager.GetString("philosophical.anthropology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical anthropology.
        /// </summary>
        public static string physical_anthropology {
            get {
                return ResourceManager.GetString("physical.anthropology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics.
        /// </summary>
        public static string physics {
            get {
                return ResourceManager.GetString("physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physiology.
        /// </summary>
        public static string physiology {
            get {
                return ResourceManager.GetString("physiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phytology.
        /// </summary>
        public static string phytology {
            get {
                return ResourceManager.GetString("phytology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phytophysiology.
        /// </summary>
        public static string phytophysiology {
            get {
                return ResourceManager.GetString("phytophysiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phytosociology.
        /// </summary>
        public static string phytosociology {
            get {
                return ResourceManager.GetString("phytosociology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phytotomy.
        /// </summary>
        public static string phytotomy {
            get {
                return ResourceManager.GetString("phytotomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date posted.
        /// </summary>
        public static string posted {
            get {
                return ResourceManager.GetString("posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My questions.
        /// </summary>
        public static string prifile_myquestions {
            get {
                return ResourceManager.GetString("prifile.myquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact administration.
        /// </summary>
        public static string profile_contact_admin {
            get {
                return ResourceManager.GetString("profile.contact.admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string profile_edit_email {
            get {
                return ResourceManager.GetString("profile.edit.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string profile_edit_er_email_invalid {
            get {
                return ResourceManager.GetString("profile.edit.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string profile_edit_er_email_required {
            get {
                return ResourceManager.GetString("profile.edit.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fist name is required.
        /// </summary>
        public static string profile_edit_er_fname_required {
            get {
                return ResourceManager.GetString("profile.edit.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string profile_edit_er_lname {
            get {
                return ResourceManager.GetString("profile.edit.er.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string profile_edit_fname {
            get {
                return ResourceManager.GetString("profile.edit.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string profile_edit_lname {
            get {
                return ResourceManager.GetString("profile.edit.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string profile_edit_save {
            get {
                return ResourceManager.GetString("profile.edit.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My answers.
        /// </summary>
        public static string profile_myanswers {
            get {
                return ResourceManager.GetString("profile.myanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My articles.
        /// </summary>
        public static string profile_myarticles {
            get {
                return ResourceManager.GetString("profile.myarticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My comments.
        /// </summary>
        public static string profile_mycomment {
            get {
                return ResourceManager.GetString("profile.mycomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New answers.
        /// </summary>
        public static string profile_newanswers {
            get {
                return ResourceManager.GetString("profile.newanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New articles.
        /// </summary>
        public static string profile_newarticles {
            get {
                return ResourceManager.GetString("profile.newarticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comments.
        /// </summary>
        public static string profile_newcomments {
            get {
                return ResourceManager.GetString("profile.newcomments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New questions.
        /// </summary>
        public static string profile_newquestions {
            get {
                return ResourceManager.GetString("profile.newquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string question_create_modal_select {
            get {
                return ResourceManager.GetString("question.create.modal.select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select disciplines.
        /// </summary>
        public static string question_create_select_disciplines {
            get {
                return ResourceManager.GetString("question.create.select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select disciplines for question.
        /// </summary>
        public static string question_create_select_question_disciplines {
            get {
                return ResourceManager.GetString("question.create.select.question.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one discipline should be selected.
        /// </summary>
        public static string question_disciplines_err_required {
            get {
                return ResourceManager.GetString("question.disciplines.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search keywords.
        /// </summary>
        public static string question_search_keyword {
            get {
                return ResourceManager.GetString("question.search.keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions search.
        /// </summary>
        public static string question_search_title {
            get {
                return ResourceManager.GetString("question.search.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions search.
        /// </summary>
        public static string question_serach {
            get {
                return ResourceManager.GetString("question.serach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select disciplines.
        /// </summary>
        public static string question_serach_select_disciplines {
            get {
                return ResourceManager.GetString("question.serach.select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show question.
        /// </summary>
        public static string question_show {
            get {
                return ResourceManager.GetString("question.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text.
        /// </summary>
        public static string question_text {
            get {
                return ResourceManager.GetString("question.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text is required.
        /// </summary>
        public static string question_text_err_required {
            get {
                return ResourceManager.GetString("question.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title.
        /// </summary>
        public static string question_title {
            get {
                return ResourceManager.GetString("question.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title is required.
        /// </summary>
        public static string question_title_err_required {
            get {
                return ResourceManager.GetString("question.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string registration__btn_register {
            get {
                return ResourceManager.GetString("registration..btn.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string registration_bidthdate {
            get {
                return ResourceManager.GetString("registration.bidthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified date is invalid.
        /// </summary>
        public static string registration_date_err_invalid {
            get {
                return ResourceManager.GetString("registration.date.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string registration_email {
            get {
                return ResourceManager.GetString("registration.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with specified email already exists.
        /// </summary>
        public static string registration_er_email_exists {
            get {
                return ResourceManager.GetString("registration.er.email.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is not a valid email address.
        /// </summary>
        public static string registration_er_email_invalid {
            get {
                return ResourceManager.GetString("registration.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string registration_er_email_required {
            get {
                return ResourceManager.GetString("registration.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string registration_er_fname_required {
            get {
                return ResourceManager.GetString("registration.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string registration_er_lname_required {
            get {
                return ResourceManager.GetString("registration.er.lname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have least 6 symbols.
        /// </summary>
        public static string registration_er_pwd_length {
            get {
                return ResourceManager.GetString("registration.er.pwd.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pssword is required.
        /// </summary>
        public static string registration_er_pwd_required {
            get {
                return ResourceManager.GetString("registration.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match the password.
        /// </summary>
        public static string registration_er_pwdconf_notmatch {
            get {
                return ResourceManager.GetString("registration.er.pwdconf.notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required.
        /// </summary>
        public static string registration_er_pwdconf_required {
            get {
                return ResourceManager.GetString("registration.er.pwdconf.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is required.
        /// </summary>
        public static string registration_er_university_required {
            get {
                return ResourceManager.GetString("registration.er.university.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string registration_fname {
            get {
                return ResourceManager.GetString("registration.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register if you do not have an account.
        /// </summary>
        public static string registration_lbl_register {
            get {
                return ResourceManager.GetString("registration.lbl.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string registration_lname {
            get {
                return ResourceManager.GetString("registration.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string registration_pwd {
            get {
                return ResourceManager.GetString("registration.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string registration_pwdconf {
            get {
                return ResourceManager.GetString("registration.pwdconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string registration_submit {
            get {
                return ResourceManager.GetString("registration.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string registration_univercity {
            get {
                return ResourceManager.GetString("registration.univercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religious anthropology.
        /// </summary>
        public static string religious_anthropology {
            get {
                return ResourceManager.GetString("religious.anthropology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove answer.
        /// </summary>
        public static string remove_answer {
            get {
                return ResourceManager.GetString("remove.answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove comment.
        /// </summary>
        public static string remove_comment {
            get {
                return ResourceManager.GetString("remove.comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove note.
        /// </summary>
        public static string remove_note {
            get {
                return ResourceManager.GetString("remove.note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search result.
        /// </summary>
        public static string search_result_empty {
            get {
                return ResourceManager.GetString("search.result.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select disciplines.
        /// </summary>
        public static string select_disciplines {
            get {
                return ResourceManager.GetString("select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        public static string select_image {
            get {
                return ResourceManager.GetString("select.image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.and cultural anthropology.
        /// </summary>
        public static string social_and_cultural_anthropology {
            get {
                return ResourceManager.GetString("social.and.cultural.anthropology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermodynamics.
        /// </summary>
        public static string thermodynamics {
            get {
                return ResourceManager.GetString("thermodynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy: Home.
        /// </summary>
        public static string title_home {
            get {
                return ResourceManager.GetString("title.home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy: Profile.
        /// </summary>
        public static string title_profile {
            get {
                return ResourceManager.GetString("title.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topology.
        /// </summary>
        public static string topology {
            get {
                return ResourceManager.GetString("topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string user_birthdate {
            get {
                return ResourceManager.GetString("user.birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date is required.
        /// </summary>
        public static string user_birthdate_err_required {
            get {
                return ResourceManager.GetString("user.birthdate.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplines description.
        /// </summary>
        public static string user_edit_disciplines_description {
            get {
                return ResourceManager.GetString("user.edit.disciplines.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplines settings.
        /// </summary>
        public static string user_edit_disciplines_title {
            get {
                return ResourceManager.GetString("user.edit.disciplines.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main profile settigs.
        /// </summary>
        public static string user_edit_title {
            get {
                return ResourceManager.GetString("user.edit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string user_email {
            get {
                return ResourceManager.GetString("user.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified email is not an email address.
        /// </summary>
        public static string user_email_err_invalid {
            get {
                return ResourceManager.GetString("user.email.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string user_email_err_required {
            get {
                return ResourceManager.GetString("user.email.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string user_firstname {
            get {
                return ResourceManager.GetString("user.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string user_firstname_err_requiered {
            get {
                return ResourceManager.GetString("user.firstname.err.requiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string user_lastname {
            get {
                return ResourceManager.GetString("user.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string user_lastname_err_required {
            get {
                return ResourceManager.GetString("user.lastname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string user_photo {
            get {
                return ResourceManager.GetString("user.photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string user_university {
            get {
                return ResourceManager.GetString("user.university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is required.
        /// </summary>
        public static string user_university_err_required {
            get {
                return ResourceManager.GetString("user.university.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the &quot;Academy&quot;!.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your disciplines.
        /// </summary>
        public static string your_disciplines {
            get {
                return ResourceManager.GetString("your.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zootom.
        /// </summary>
        public static string zootomy {
            get {
                return ResourceManager.GetString("zootomy", resourceCulture);
            }
        }
    }
}
