//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Validation.Dictionaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Academy.Validation.Dictionaries.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Социальная сеть для ученых «Академия» создана в 2013 году..
        /// </summary>
        public static string about_p1 {
            get {
                return ResourceManager.GetString("about.p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашей основной целью является создание пространства, которое бы объединяло работы будущих и настоящих ученых всего мира, давало возможность пользования публикациями..
        /// </summary>
        public static string about_p2 {
            get {
                return ResourceManager.GetString("about.p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В технические возможности сайта входят загрузка, скачивание и комментирование публикаций, создание своего профиля с личной информацией, конфиденциальность которой гарантируется. Вы также можете задать любой интересующий вас вопрос и получить на него ответ, либо оставить ответ самому. Оставляйте заметки в собственном профиле, чтобы помнить важные мероприятия!.
        /// </summary>
        public static string about_p3 {
            get {
                return ResourceManager.GetString("about.p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы хотели организовать доступный из любой точки мира ресурс, который приносил бы пользу всем желающим получить достоверную информацию из проверенных источников..
        /// </summary>
        public static string about_p4 {
            get {
                return ResourceManager.GetString("about.p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интернет-сайт «Академия» специфичен. Нашей целевой аудиторией являются люди с высшим образованием и ученой степенью (учеными степенями), а также аспиранты, магистры — и все те, кто в будущем стремится попасть в социальную категорию «ученых». Зарегистрировавшись здесь, вы всегда сможете найти нужную вам информацию в сферах Математики, Физики, Биологии, а такжепросмотреть вопросы/ ответы коллег и людей по интересам..
        /// </summary>
        public static string about_p5 {
            get {
                return ResourceManager.GetString("about.p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете воспользоваться сменой языков, чтобы просматривать «Академию» на удобном вам языке. Загрузите личное фото, чтобы вас могли узнать читатели. Найти необходимый вам материал, воспользовавшись поиском. Комментировать публикации и таким образом облегчать поиск остальным, подписавшимся на данную тематику. Оставляйте интересующие вас дисциплины и получайте обновления по всему происходящему в них!.
        /// </summary>
        public static string about_p6 {
            get {
                return ResourceManager.GetString("about.p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для наилучшей работы сайта воспользуйтесь формой обратной связи в разделе Контакты. Мы будем рады любым предложениям и отзывам, ответим на все вопросы..
        /// </summary>
        public static string about_p7 {
            get {
                return ResourceManager.GetString("about.p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как и любой начинающий проект, мы собираемся расти, предоставляя все новые и новые возможности пользователям. Спасибо, что выбрали нас!.
        /// </summary>
        public static string about_p8 {
            get {
                return ResourceManager.GetString("about.p8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Социальная сеть для ученых «Академия». Всегда на пульсе науки! © 2013.
        /// </summary>
        public static string about_p9 {
            get {
                return ResourceManager.GetString("about.p9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую статью.
        /// </summary>
        public static string add_new_article {
            get {
                return ResourceManager.GetString("add.new.article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую заметку.
        /// </summary>
        public static string add_new_note {
            get {
                return ResourceManager.GetString("add.new.note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить ответ.
        /// </summary>
        public static string answer_add {
            get {
                return ResourceManager.GetString("answer.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст ответа.
        /// </summary>
        public static string answer_text {
            get {
                return ResourceManager.GetString("answer.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести текст ответа.
        /// </summary>
        public static string answer_text_err_required {
            get {
                return ResourceManager.GetString("answer.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать ответы.
        /// </summary>
        public static string answers_show {
            get {
                return ResourceManager.GetString("answers.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить автора.
        /// </summary>
        public static string article_create_add_author {
            get {
                return ResourceManager.GetString("article.create.add.author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string article_create_modal_select {
            get {
                return ResourceManager.GetString("article.create.modal.select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дисциплины для статьи.
        /// </summary>
        public static string article_create_select_article_disciplines {
            get {
                return ResourceManager.GetString("article.create.select.article.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дисциплины.
        /// </summary>
        public static string article_create_select_disciplines {
            get {
                return ResourceManager.GetString("article.create.select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание статьи.
        /// </summary>
        public static string article_description {
            get {
                return ResourceManager.GetString("article.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести описание статьи.
        /// </summary>
        public static string article_description_err_required {
            get {
                return ResourceManager.GetString("article.description.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья должна относиться хотя бы к одной дисциплине.
        /// </summary>
        public static string article_disciplines_err_required {
            get {
                return ResourceManager.GetString("article.disciplines.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл статьи.
        /// </summary>
        public static string article_file {
            get {
                return ResourceManager.GetString("article.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string article_search_author {
            get {
                return ResourceManager.GetString("article.search.author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание статьи.
        /// </summary>
        public static string article_search_description {
            get {
                return ResourceManager.GetString("article.search.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок статьи.
        /// </summary>
        public static string article_search_title {
            get {
                return ResourceManager.GetString("article.search.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать статью.
        /// </summary>
        public static string article_show {
            get {
                return ResourceManager.GetString("article.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла статьи в pdf.
        /// </summary>
        public static string article_source {
            get {
                return ResourceManager.GetString("article.source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести имя источника файла.
        /// </summary>
        public static string article_source_err_required {
            get {
                return ResourceManager.GetString("article.source.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок статьи.
        /// </summary>
        public static string article_title {
            get {
                return ResourceManager.GetString("article.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести заголовок статьи.
        /// </summary>
        public static string article_title_err_required {
            get {
                return ResourceManager.GetString("article.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вопрос.
        /// </summary>
        public static string ask_question {
            get {
                return ResourceManager.GetString("ask.question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Емэйл.
        /// </summary>
        public static string author_email {
            get {
                return ResourceManager.GetString("author.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный емэйл не является емэйл-адресом.
        /// </summary>
        public static string author_email_err_invalid {
            get {
                return ResourceManager.GetString("author.email.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести емэйл.
        /// </summary>
        public static string author_email_err_required {
            get {
                return ResourceManager.GetString("author.email.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string author_firstname {
            get {
                return ResourceManager.GetString("author.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести имя.
        /// </summary>
        public static string author_firstname_err_required {
            get {
                return ResourceManager.GetString("author.firstname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string author_lastname {
            get {
                return ResourceManager.GetString("author.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести фамилию.
        /// </summary>
        public static string author_lastname_err_required {
            get {
                return ResourceManager.GetString("author.lastname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rus.swf.
        /// </summary>
        public static string banner {
            get {
                return ResourceManager.GetString("banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В случае, если у вас возникли проблемы с использованием ресурса, вопросы, пожелания, мы всегда готовы выйти на связь с вами!.
        /// </summary>
        public static string cintacts_p2 {
            get {
                return ResourceManager.GetString("cintacts.p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментировать.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить комментарий.
        /// </summary>
        public static string comment_add {
            get {
                return ResourceManager.GetString("comment.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст комментария.
        /// </summary>
        public static string comment_text {
            get {
                return ResourceManager.GetString("comment.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести текст комментария.
        /// </summary>
        public static string comment_text_err_required {
            get {
                return ResourceManager.GetString("comment.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать комментарии.
        /// </summary>
        public static string comments_show {
            get {
                return ResourceManager.GetString("comments.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемы пользователи!.
        /// </summary>
        public static string contacts_p1 {
            get {
                return ResourceManager.GetString("contacts.p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо вам!.
        /// </summary>
        public static string contacts_p10 {
            get {
                return ResourceManager.GetString("contacts.p10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите администрации сайта на следующие электронные ящики:.
        /// </summary>
        public static string contacts_p3 {
            get {
                return ResourceManager.GetString("contacts.p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alololo@gmail.com.
        /// </summary>
        public static string contacts_p4 {
            get {
                return ResourceManager.GetString("contacts.p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kororo@gmail.com.
        /// </summary>
        public static string contacts_p5 {
            get {
                return ResourceManager.GetString("contacts.p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или позвоните нам по телефонам:.
        /// </summary>
        public static string contacts_p6 {
            get {
                return ResourceManager.GetString("contacts.p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +25 (269) 12-3563.
        /// </summary>
        public static string contacts_p7 {
            get {
                return ResourceManager.GetString("contacts.p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +74 (021) 13-5684.
        /// </summary>
        public static string contacts_p8 {
            get {
                return ResourceManager.GetString("contacts.p8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +89 (589) 14-5692.
        /// </summary>
        public static string contacts_p9 {
            get {
                return ResourceManager.GetString("contacts.p9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 Академия.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисциплины.
        /// </summary>
        public static string disciplines {
            get {
                return ResourceManager.GetString("disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string external_menu_about {
            get {
                return ResourceManager.GetString("external.menu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статьи.
        /// </summary>
        public static string external_menu_articles {
            get {
                return ResourceManager.GetString("external.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string external_menu_contacts {
            get {
                return ResourceManager.GetString("external.menu.contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы.
        /// </summary>
        public static string external_menu_questions {
            get {
                return ResourceManager.GetString("external.menu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АКАДЕМИЯ.
        /// </summary>
        public static string external_title {
            get {
                return ResourceManager.GetString("external.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск статей.
        /// </summary>
        public static string internal_menu_articles {
            get {
                return ResourceManager.GetString("internal.menu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string internal_menu_exit {
            get {
                return ResourceManager.GetString("internal.menu.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки профиля.
        /// </summary>
        public static string internal_menu_profile {
            get {
                return ResourceManager.GetString("internal.menu.profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы и ответы.
        /// </summary>
        public static string internal_menu_questions {
            get {
                return ResourceManager.GetString("internal.menu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АКАДЕМИЯ.
        /// </summary>
        public static string internal_title {
            get {
                return ResourceManager.GetString("internal.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_eng {
            get {
                return ResourceManager.GetString("lang.eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string lang_language {
            get {
                return ResourceManager.GetString("lang.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string lang_rus {
            get {
                return ResourceManager.GetString("lang.rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string login_btn_login {
            get {
                return ResourceManager.GetString("login.btn.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Емэйл.
        /// </summary>
        public static string login_email {
            get {
                return ResourceManager.GetString("login.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно введен емэйл.
        /// </summary>
        public static string login_er_email_invalid {
            get {
                return ResourceManager.GetString("login.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите емэйл для входа.
        /// </summary>
        public static string login_er_email_required {
            get {
                return ResourceManager.GetString("login.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль для входа.
        /// </summary>
        public static string login_er_pwd_required {
            get {
                return ResourceManager.GetString("login.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя или пароль неверны.
        /// </summary>
        public static string login_err_failed {
            get {
                return ResourceManager.GetString("login.err.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string login_forgotpwd {
            get {
                return ResourceManager.GetString("login.forgotpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизоваться.
        /// </summary>
        public static string login_lbl_signin {
            get {
                return ResourceManager.GetString("login.lbl.signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string login_pwd {
            get {
                return ResourceManager.GetString("login.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставаться в системе.
        /// </summary>
        public static string login_remember {
            get {
                return ResourceManager.GetString("login.remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string login_submit {
            get {
                return ResourceManager.GetString("login.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo_rus.png.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string mainmenu_about {
            get {
                return ResourceManager.GetString("mainmenu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск статей.
        /// </summary>
        public static string mainmenu_articles {
            get {
                return ResourceManager.GetString("mainmenu.articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string mainmenu_contacts {
            get {
                return ResourceManager.GetString("mainmenu.contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы и ответы.
        /// </summary>
        public static string mainmenu_questions {
            get {
                return ResourceManager.GetString("mainmenu.questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Январь.
        /// </summary>
        public static string month1 {
            get {
                return ResourceManager.GetString("month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октябрь.
        /// </summary>
        public static string month10 {
            get {
                return ResourceManager.GetString("month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноябрь.
        /// </summary>
        public static string month11 {
            get {
                return ResourceManager.GetString("month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декабрь.
        /// </summary>
        public static string month12 {
            get {
                return ResourceManager.GetString("month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февраль.
        /// </summary>
        public static string month2 {
            get {
                return ResourceManager.GetString("month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        public static string month3 {
            get {
                return ResourceManager.GetString("month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апрель.
        /// </summary>
        public static string month4 {
            get {
                return ResourceManager.GetString("month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        public static string month5 {
            get {
                return ResourceManager.GetString("month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июнь.
        /// </summary>
        public static string month6 {
            get {
                return ResourceManager.GetString("month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июль.
        /// </summary>
        public static string month7 {
            get {
                return ResourceManager.GetString("month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Август.
        /// </summary>
        public static string month8 {
            get {
                return ResourceManager.GetString("month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сентябрь.
        /// </summary>
        public static string month9 {
            get {
                return ResourceManager.GetString("month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить заметку.
        /// </summary>
        public static string note_add {
            get {
                return ResourceManager.GetString("note.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст заметки.
        /// </summary>
        public static string note_text {
            get {
                return ResourceManager.GetString("note.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести текст заметки.
        /// </summary>
        public static string note_text_err_required {
            get {
                return ResourceManager.GetString("note.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок заметки.
        /// </summary>
        public static string note_title {
            get {
                return ResourceManager.GetString("note.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести заголовок заметки.
        /// </summary>
        public static string note_title_err_required {
            get {
                return ResourceManager.GetString("note.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата публикации.
        /// </summary>
        public static string posted {
            get {
                return ResourceManager.GetString("posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои вопросы.
        /// </summary>
        public static string prifile_myquestions {
            get {
                return ResourceManager.GetString("prifile.myquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с администрацией.
        /// </summary>
        public static string profile_contact_admin {
            get {
                return ResourceManager.GetString("profile.contact.admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Емэйл.
        /// </summary>
        public static string profile_edit_email {
            get {
                return ResourceManager.GetString("profile.edit.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный емэйл-адрес.
        /// </summary>
        public static string profile_edit_er_email_invalid {
            get {
                return ResourceManager.GetString("profile.edit.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести емэйл.
        /// </summary>
        public static string profile_edit_er_email_required {
            get {
                return ResourceManager.GetString("profile.edit.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести имя.
        /// </summary>
        public static string profile_edit_er_fname_required {
            get {
                return ResourceManager.GetString("profile.edit.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести фамилию.
        /// </summary>
        public static string profile_edit_er_lname {
            get {
                return ResourceManager.GetString("profile.edit.er.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string profile_edit_fname {
            get {
                return ResourceManager.GetString("profile.edit.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string profile_edit_lname {
            get {
                return ResourceManager.GetString("profile.edit.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string profile_edit_save {
            get {
                return ResourceManager.GetString("profile.edit.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои ответы.
        /// </summary>
        public static string profile_myanswers {
            get {
                return ResourceManager.GetString("profile.myanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои статьи.
        /// </summary>
        public static string profile_myarticles {
            get {
                return ResourceManager.GetString("profile.myarticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои комментарии.
        /// </summary>
        public static string profile_mycomment {
            get {
                return ResourceManager.GetString("profile.mycomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые ответы.
        /// </summary>
        public static string profile_newanswers {
            get {
                return ResourceManager.GetString("profile.newanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые статьи.
        /// </summary>
        public static string profile_newarticles {
            get {
                return ResourceManager.GetString("profile.newarticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые комментарии.
        /// </summary>
        public static string profile_newcomments {
            get {
                return ResourceManager.GetString("profile.newcomments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые вопросы.
        /// </summary>
        public static string profile_newquestions {
            get {
                return ResourceManager.GetString("profile.newquestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовать.
        /// </summary>
        public static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string question_create_modal_select {
            get {
                return ResourceManager.GetString("question.create.modal.select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дисциплины.
        /// </summary>
        public static string question_create_select_disciplines {
            get {
                return ResourceManager.GetString("question.create.select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дисциплины для вопроса.
        /// </summary>
        public static string question_create_select_question_disciplines {
            get {
                return ResourceManager.GetString("question.create.select.question.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотя бы одна дисциплина должна быть выбрана.
        /// </summary>
        public static string question_disciplines_err_required {
            get {
                return ResourceManager.GetString("question.disciplines.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключевые слова поиска.
        /// </summary>
        public static string question_search_keyword {
            get {
                return ResourceManager.GetString("question.search.keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск вопросов.
        /// </summary>
        public static string question_search_title {
            get {
                return ResourceManager.GetString("question.search.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск вопросов.
        /// </summary>
        public static string question_serach {
            get {
                return ResourceManager.GetString("question.serach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дисциплины.
        /// </summary>
        public static string question_serach_select_disciplines {
            get {
                return ResourceManager.GetString("question.serach.select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать вопросы.
        /// </summary>
        public static string question_show {
            get {
                return ResourceManager.GetString("question.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст вопроса.
        /// </summary>
        public static string question_text {
            get {
                return ResourceManager.GetString("question.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести текст вопроса.
        /// </summary>
        public static string question_text_err_required {
            get {
                return ResourceManager.GetString("question.text.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок вопроса.
        /// </summary>
        public static string question_title {
            get {
                return ResourceManager.GetString("question.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести заголовок вопроса.
        /// </summary>
        public static string question_title_err_required {
            get {
                return ResourceManager.GetString("question.title.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string registration_bidthdate {
            get {
                return ResourceManager.GetString("registration.bidthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string registration_btn_register {
            get {
                return ResourceManager.GetString("registration.btn.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата неверна.
        /// </summary>
        public static string registration_date_err_invalid {
            get {
                return ResourceManager.GetString("registration.date.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Емэйл.
        /// </summary>
        public static string registration_email {
            get {
                return ResourceManager.GetString("registration.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким емэйлом уже существует.
        /// </summary>
        public static string registration_er_email_exists {
            get {
                return ResourceManager.GetString("registration.er.email.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный емэйл-адрес.
        /// </summary>
        public static string registration_er_email_invalid {
            get {
                return ResourceManager.GetString("registration.er.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести емэйл.
        /// </summary>
        public static string registration_er_email_required {
            get {
                return ResourceManager.GetString("registration.er.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести имя.
        /// </summary>
        public static string registration_er_fname_required {
            get {
                return ResourceManager.GetString("registration.er.fname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести фамилию.
        /// </summary>
        public static string registration_er_lname_required {
            get {
                return ResourceManager.GetString("registration.er.lname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы 6 символов.
        /// </summary>
        public static string registration_er_pwd_length {
            get {
                return ResourceManager.GetString("registration.er.pwd.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести пароль.
        /// </summary>
        public static string registration_er_pwd_required {
            get {
                return ResourceManager.GetString("registration.er.pwd.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля не совпадает с паролем.
        /// </summary>
        public static string registration_er_pwdconf_notmatch {
            get {
                return ResourceManager.GetString("registration.er.pwdconf.notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется подтвердить пароль.
        /// </summary>
        public static string registration_er_pwdconf_required {
            get {
                return ResourceManager.GetString("registration.er.pwdconf.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести университет.
        /// </summary>
        public static string registration_er_university_required {
            get {
                return ResourceManager.GetString("registration.er.university.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string registration_fname {
            get {
                return ResourceManager.GetString("registration.fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрируйтесь, если у вас нет аккаунта.
        /// </summary>
        public static string registration_lbl_register {
            get {
                return ResourceManager.GetString("registration.lbl.register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string registration_lname {
            get {
                return ResourceManager.GetString("registration.lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string registration_pwd {
            get {
                return ResourceManager.GetString("registration.pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string registration_pwdconf {
            get {
                return ResourceManager.GetString("registration.pwdconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string registration_submit {
            get {
                return ResourceManager.GetString("registration.submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет.
        /// </summary>
        public static string registration_univercity {
            get {
                return ResourceManager.GetString("registration.univercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить ответ.
        /// </summary>
        public static string remove_answer {
            get {
                return ResourceManager.GetString("remove.answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить комментарий.
        /// </summary>
        public static string remove_comment {
            get {
                return ResourceManager.GetString("remove.comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить заметку.
        /// </summary>
        public static string remove_note {
            get {
                return ResourceManager.GetString("remove.note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дисциплины.
        /// </summary>
        public static string select_disciplines {
            get {
                return ResourceManager.GetString("select.disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать изображение.
        /// </summary>
        public static string select_image {
            get {
                return ResourceManager.GetString("select.image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string user_birthdate {
            get {
                return ResourceManager.GetString("user.birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести дату рождения.
        /// </summary>
        public static string user_birthdate_err_required {
            get {
                return ResourceManager.GetString("user.birthdate.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание дисциплин.
        /// </summary>
        public static string user_edit_disciplines_description {
            get {
                return ResourceManager.GetString("user.edit.disciplines.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки дисциплин.
        /// </summary>
        public static string user_edit_disciplines_title {
            get {
                return ResourceManager.GetString("user.edit.disciplines.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки профиля.
        /// </summary>
        public static string user_edit_title {
            get {
                return ResourceManager.GetString("user.edit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Емэйл.
        /// </summary>
        public static string user_email {
            get {
                return ResourceManager.GetString("user.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный емэйл-адрес.
        /// </summary>
        public static string user_email_err_invalid {
            get {
                return ResourceManager.GetString("user.email.err.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести емэйл.
        /// </summary>
        public static string user_email_err_required {
            get {
                return ResourceManager.GetString("user.email.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string user_firstname {
            get {
                return ResourceManager.GetString("user.firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести имя.
        /// </summary>
        public static string user_firstname_err_requiered {
            get {
                return ResourceManager.GetString("user.firstname.err.requiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string user_lastname {
            get {
                return ResourceManager.GetString("user.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести фамилию.
        /// </summary>
        public static string user_lastname_err_required {
            get {
                return ResourceManager.GetString("user.lastname.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string user_photo {
            get {
                return ResourceManager.GetString("user.photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет.
        /// </summary>
        public static string user_university {
            get {
                return ResourceManager.GetString("user.university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется ввести университет.
        /// </summary>
        public static string user_university_err_required {
            get {
                return ResourceManager.GetString("user.university.err.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в &quot;Академию&quot;!.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши дисциплины.
        /// </summary>
        public static string your_disciplines {
            get {
                return ResourceManager.GetString("your.disciplines", resourceCulture);
            }
        }
    }
}
